### ISSUE TITLE
Allow dataset formats to be valid in LOAD with no INTO

### ISSUE THREAD

**Issue by afs** [w3c/sparql-update#41]
Formats: TriG, N-Quads, JSON-LD.

**Comment by afs** [comment]
This is following through on the RDF 1.1 Concept definition of RDF Dataset allowing blank nodes for graph names.

See also https://github.com/w3c/sparql-query/pull/152

**Comment by Tpt** [comment]
JSON-LD is often used as a graph-only format. Maybe we can allow `INTO` for all formats stating that `INTO` maps the source default graph into the graph given by `INTO`.

**Comment by afs** [comment]
Yes, that seems natural.

All the formats allow a graph-only subset.

The one I come across sometimes is nquads as a dataset dump and the dataset only has a default graph.

**Comment by pfps** [comment]
What is supposed to happen in this case?

**Comment by afs** [comment]
> What is supposed to happen in this case?
Quads are loaded into the dataset.

> Are dataset formats acceptable if there is an INTO?

No.

Only the case of LOAD without INTO.

At the moment, that loads triple formats into the default graph.

**Comment by afs** [comment]
> JSON-LD is often used as a graph-only format. Maybe we can allow `INTO` for all formats stating that `INTO` maps the source default graph into the graph given by `INTO`.

That `INTO` case is unfortunate. What happens if that JSON-LD does contains both default graph and named graphs? This can't be determined ahead of time.

We can treat it as a separate issue (if anyone wants to raise it).

For this issue, its only for without INTO.

**Comment by kasei** [comment]
> On reconsideration, that `INTO` case is unfortunate. What happens if that JSON-LD does contains both default graph and named graphs? This can't be determined ahead of time.

I think `INTO` should only work with triple formats, and we should consider using `WITH` together with `LOAD` to adjust which graph triples load by default when loading a dataset.

**Comment by afs** [comment]
[WG Resolution](https://www.w3.org/2024/12/05-rdf-star-minutes.html#5a1c) from the meeting of 2024-12-05:

> RESOLUTION: Continue with https://github.com/w3c/sparql-update/issues/41.

**Comment by lisp** [comment]
Here are two tables which indicate the disposition for content included in each category of
the combinations between
<dl>
  <dt>operation graph</dt>
  <dd>This concerns  the graph specified by the operation.
    That would be a protocol graph present in a graph store protocol url
    or the graph designator in a SPARQL load into clause.</dd>
  <dt> content graph</dt>
  <dd>This is the graph present in the content.
  It applies with quad documents, uch as application/n-quads or applicaiton/trix</dd>
</dl>

In the first table, one applies the logic that the latest specification for the value should supersede any earlier specification and follows the control flow model, that the content creation precedes the operation, which leads to the following effects.

<table border="1">
  <tr >
<th >operation graph designator<th  >content type<th  >effective graph</tr>
<tr >
  <td>-</td>
  <td>n-triples, rdf+xml</td>
  <td > <code><b>PATCH</b></code>: <code><i>default</i></code> <br /> <code><b>POST</b></code>: <code><i>generated</i></code><br /> <code><b>PUT</b></code>: <code><i>default</i></code> </tr>
  <tr >
    <td>-</td>
    <td >n-quad, trix <td > <code><i>statement</i></code></td>
  </tr>

  <tr>
    <td><code><b>default</b></code>
  <td>n-triples, rdf+xml
  <td ><code><i>default</i></code></tr>
<tr >
    <td><code><b>default</b></code>
  <td  >n-quads, trix
  <td ><code><i>default</i></code></tr>

<tr >
  <td><code><b>graph=</b><i>protocol</i></code>
  <td>n-triples, rdf+xml
  <td><code><i>protocol</i></code></tr>
<tr >
    <td><code><b>graph=</b><i>protocol</i></code>
  <td  >n-quads, trix
  <td><code><i>protocol</i></code></tr>

<tr >
  <td><code><i>protocol</i></code> GSP direct graph</td>
  <td>n-triples, rdf+xml
  <td><code><i>protocol</i></code></tr>
<tr >
  <td><code><i>protocol</i></code> GSP direct graph</td>
  <td  >n-quads, trix
  <td><code><i>protocol</i></code></tr>
</table>


<p>
The pull request suggest a logic which rejects over-constrained operations.

<table border="1">
  <tr >
<th >operation graph designator<th  >content type<th  >effective graph</tr>
<tr >
  <td>-</td>
  <td>n-triples, rdf+xml</td>
  <td > <code><b>PATCH</b></code>: <code><i>default</i></code> <br /> <code><b>POST</b></code>: <code><i>generated</i></code><br /> <code><b>PUT</b></code>: <code><i>default</i></code>
    <br />  <code><b>LOAD</b></code>: <code><i>default</i></tr>
  <tr >
    <td>-</td>
    <td >n-quad, trix <td > <code><i>statement</i></code></td>
  </tr>

  <tr>
    <td><code><b>default</b></code>
  <td>n-triples, rdf+xml
  <td ><code><i>default</i></code></tr>
<tr >
    <td><code><b>default</b></code>
  <td  >n-quads, trix
  <td ><code><i>error</i></code></tr>

<tr >
  <td><code><b>graph=</b><i>protocol</i></code>
  <td>n-triples, rdf+xml
  <td><code><i>protocol</i></code></tr>
<tr >
    <td><code><b>graph=</b><i>protocol</i></code>
  <td  >n-quads, trix
  <td>error</tr>

<tr >
  <td><code><i>protocol</i></code> GSP direct graph</td>
  <td>n-triples, rdf+xml
  <td><code><i>protocol</i></code></tr>
<tr >
  <td><code><i>protocol</i></code> GSP direct graph</td>
  <td  >n-quads, trix
  <td><code><i>error</i></code></tr>
</table>

**Comment by afs** [comment]
The comment above relates to https://github.com/w3c/sparql-graph-store-protocol/issues/24.

**Comment by lisp** [comment]
yes, it does relate to that, but it is not intended to be restricted to that.  
note the definition of "operation graph".
the goal is to suggest that the two recommendations should share a common logic.

**Comment by afs** [comment]
There is more material in GSP (Graph Store Protocol) related to the topic:

e.g.
https://www.w3.org/TR/sparql12-graph-store-protocol/#graph-management
https://www.w3.org/TR/sparql12-graph-store-protocol/#indirect-graph-identification

GSP uses SPARQL Update (and Query) to define its operation in some places.
