### ISSUE TITLE
No more links inside definitions

### ISSUE THREAD

**Issue by rubensworks** [w3c/sparql-update#8]
When working on #7, I noticed that the current version does not include links inside definitions anymore.

For example:
Old: https://www.w3.org/TR/sparql11-update/#deleteInsert
New: https://w3c.github.io/sparql-update/spec/#deleteInsert

The links are still there in the source, but they don't work anymore in the browser.

I suspect this is due to a respec change, but not sure yet what causes it.

@afs I suspect other specs may suffer from similar problems.

**Comment by afs** [comment]
Yes, I can see what you see.

reSpec rewrites `<a href=` 

One change we will need is `href="http://www.w3.org/TR/sparql11-query/` `data-cite="SPARQL12-QUERY`

but the problem isn't that.

In definitions, it seems it's the `<pre>. Turning the `<pre>` into `<div>` and I got links.

**Comment by gkellogg** [comment]
> Yes, I can see what you see.
> 
> reSpec rewrites `<a href=`
> 
> One change we will need is `href="http://www.w3.org/TR/sparql11-query/` `data-cite="SPARQL12-QUERY`
> 
> but the problem isn't that.

just to be clear, you don’t want to use both `data-cite` and `href`. The cite will create an href along with other markup.

**Comment by afs** [comment]
Clarified. It's a replacement.

**Comment by rubensworks** [comment]
I just looked into this a bit, and it looks like using `<div>` instead of `<pre>` may not be the solution we want, as it will not consider newlines when displayed. We could work around this by adding `<br>` in all definitions, but I don't think this is what we want.

I guess we want to stick with `<pre>`, and make it properly handle links/citations.
Is this something we can fix ourselves via CSS, or is this core to respec that is out of our control?

**Comment by gkellogg** [comment]
The problem you're running into is that ReSpec is using a syntax highlighter that ends up removing all the markup. Add `class="nohighlight"`, or in this case the following:

```
<pre class="defn nohighlight">( <strong>WITH</strong> <em><a href="http://www.w3.org/TR/sparql11-query/#rIRIREF">IRIref</a></em> )?
( ( <em><a href="http://www.w3.org/TR/sparql11-query/#rDeleteData">DeleteClause</a> <a href="http://www.w3.org/TR/sparql11-query/#rInsertData">InsertClause</a></em>? ) | <em><a href=
"http://www.w3.org/TR/sparql11-query/#rInsertData">InsertClause</a></em> )
( <strong>USING ( NAMED )?</strong> <em><a href="http://www.w3.org/TR/sparql11-query/#rIRIREF">IRIref</a></em> )*
<strong>WHERE</strong> <em><a href="http://www.w3.org/TR/sparql11-query/#rGroupGraphPattern">GroupGraphPattern</a></em></pre>
```
